title: Just the Docs Template
description: Access to code snippets for downloading data directly to their systems. 
theme: just-the-docs

url: https://github.com/VineethKumar7/dataeco.github.io

aux_links:
  Template Repository: https://github.com/VineethKumar7/dataeco.github.io
